repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
        exclude: .eslintrc.json
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.54.0
    hooks:
      - id: eslint
        #additional_dependencies: ['eslint-config-standard@latest', 'eslint@^8.0.1', 'eslint-plugin-import@^2.25.2', 'eslint-plugin-n@^16.1.0', 'eslint-plugin-promise@^6.0.0']
        additional_dependencies:
          - eslint@^8.51.0
          - eslint-config-prettier@^9.0.0
          - eslint-plugin-n@^16.1.0
          - eslint-plugin-import@^2.25.2
          - eslint-plugin-promise@^6.0.0
